### ISSUE TITLE
Create a GraphStream class

### ISSUE THREAD

**Issue by balidani** [vasia/gelly-streaming#1]
This class should support multiple ways to stream graph data:
- Random edge streams (with or without duplicates)
- Incidence streams
- Mutation events -- edge addition, deletion or value modification
- Others (?)

**Comment by vasia** [comment]
One thing we'll have decide here is whether GraphStream will internally be represented as a DataStream of Edges and a DataStream of Vertices or something else.
I would say let's go for this solution initially and try to figure out how to create these streams in the cases mentioned above, i.e. random edge streams, incidence streams and mutation events.

**Comment by balidani** [comment]
I think we've settled for random edge streams with duplicates for now.
