### ISSUE TITLE
Connected components merger issue

### ISSUE THREAD

**Issue by Zainab-Abbas** [vasia/gelly-streaming#13]
The reduce function is setting wrong component id in some cases

Example:
after folding we get: 
{2=[2, 4]}{3=[3, 5]}{1=[1, 3]}

reduce on this data gives:
{2=[2, 4], 5=[1, 3, 5]}

Expected output:
{2=[2, 4], 1=[1, 3, 5]}

**Comment by senorcarbone** [comment]
There is no constraint on the identifier of a connected component, it can be arbitrary. If you write a test for it just make sure that the disjoint set elements match.
