### ISSUE TITLE
Port Examples to Library Window Aggregation Functions

### ISSUE THREAD

**Issue by senorcarbone** [vasia/gelly-streaming#14]
It would be nice to offer ConnectedComponents, TriangleCount etc as library methods instead of plain examples.

We can keep the examples to demonstrate use cases on how to use these aggregation functions and add unit tests to test them.

**Comment by vasia** [comment]
+1. Let's do this like we've done it in Gelly. Make a separate "library" package and port the examples to use the provided library methods.

**Comment by vasia** [comment]
see #15
