### ISSUE TITLE
Exception at FoldFunction 

### ISSUE THREAD

**Issue by Zainab-Abbas** [vasia/gelly-streaming#16]
Following exception is thrown by updating pom file based on latest commit when we debug the code:

FoldFunction can not be a RichFunction, Please use apply(FoldFunction, WindowFunction) instead.
at
- WindowedStream.java:183
- WindowGraphAggregation.java:59
- SimpleEdgeStream.java:105

**Comment by vasia** [comment]
Thanks for opening the issue @Zainab-Abbas. Would you like to give it a try and fix it? It looks to me we can get rid of the `WrappingFunction` altogether. What do you think @senorcarbone?

**Comment by Zainab-Abbas** [comment]
I solved the issue let me create a new pull request and you can check if its correct

**Comment by vasia** [comment]
Thanks @Zainab-Abbas, I've merged.
