### ISSUE TITLE
The result of ExactTriangleCount

### ISSUE THREAD

**Issue by lilicao701** [vasia/gelly-streaming#33]
Hi, 
 I want to test ExactTriangleCount with the fellow test data in my IDEA local model , but the result I think is not right:
				new Edge<>(1, 2, NullValue.getInstance()),
				new Edge<>(2, 3, NullValue.getInstance()),
				new Edge<>(2, 6, NullValue.getInstance()),
				new Edge<>(5, 6, NullValue.getInstance()),
				new Edge<>(1, 4, NullValue.getInstance()),
				new Edge<>(5, 3, NullValue.getInstance()),
				new Edge<>(3, 4, NullValue.getInstance()),
				new Edge<>(3, 6, NullValue.getInstance()),
				new Edge<>(1, 3, NullValue.getInstance())),

In addition，the results are not the same for each run， and one time the result is like this:
1> (-1,1)
3> (6,1)
8> (2,1)
2> (3,1)
7> (1,1)
2> (3,2)
8> (4,1)
1> (-1,2)

with vertexID=3, the triangle is 4 ,not 1; so I want to know how to run this algorithm? 

thank you very much.

**Comment by vasia** [comment]
Hi @lilicao701,
is this the whole output you're getting? This is a streaming algorithm, so the more edges you see the triangles change. That's why you first see (3, 1), then (3, 2). There should also be a (3, 4) later on.

**Comment by lilicao701** [comment]
@ vasia:
   Thank you very much for  answer this problem, I find that the cause of the error, is Flink version , in my develop IDEA, the flink version is 1.1.5 (main cause of Parallelism) , when I change to Flink-1.2.0 ,the result is right.
