### ISSUE TITLE
How to develop PageRank algorithm on GellyStream

### ISSUE THREAD

**Issue by lilicao701** [vasia/gelly-streaming#36]
Hi
  I want to develop real-time  PageRank incremental algorithm, but I do not know how to implement iterative calculations, do you have some idea can help me ,Thank you.

**Comment by senorcarbone** [comment]
Hi @lilicao701!
The problem with PageRank is deeper than it seems. There are tons of requirements from the actual system side (the API is the easy part) that block this. We need native Flink support on arbitrary nested scoped iterations and adaptation of watermarks to loops. On top of that there is a need for better flow control for iterations, job termination etc.

The good news is that our team is very actively working on it so stay tuned and you might see several of these issues and libraries in Flink and also Gelly-Stream quite soon!
